name: mlflow.classification.workflow
channels:
  - conda-forge
  - defaults
  - joshburt
dependencies:
  - python=3.10.8
  - mlflow=2.0.1
  - python-dotenv
  - click
  - make
  - tensorflow=2.10.0
  - anaconda.enterprise.server.common.sdk=0.1.0
  - anaconda.enterprise.mlops.sdk=0.2.0
  - jupyter=1.0.0
  - black
  - black-jupyter
  - coverage
  - isort
  - pydantic
  - pylint
  - anaconda-client
  - shapeandshare.command.runner
  - pip:
    - python-mnist
